language:  cpp
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
  homebrew:
    taps:
      - facebook/fb
    packages:
      - buck

os:
  - linux
  - osx

env:
  - BUCKAROO_VERSION=v2.0.0

osx_image: xcode9.3

before_install:
  - ./travis/before-install-$TRAVIS_OS_NAME.sh

script:
  - ./bin/buckaroo install
  - ./bin/buck build -c ui.superconsole=DISABLED //:protobuf
  - ./bin/buck run -c ui.superconsole=DISABLED //:protoc
